name: i18next_code_gen
description: The dart class generator from i18next resource file
version: 1.0.0
repository: https://github.com/svenopdehipt/i18next_code_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  glob: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^3.0.0
